"""Generate docs/testing/generated/launch-flow-truth.md from the app source code.

Authority list emitted per surface:
  - testTag values used in Compose
  - stringResource and literal text used in launch-critical Composables
  - error codes referenced (UI-* / GPU-*) by Composables
  - stage-machine transitions from FirstSessionStage
  - keep-alive options, runtime profiles, runtime status labels

This is the ONE document later sub-agents and Maestro flow audits compare
against. It must be regenerated whenever code changes.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "apps/mobile-android/src/main/kotlin/com/pocketagent/android"
RES = REPO / "apps/mobile-android/src/main/res/values"
OUT = REPO / "docs/testing/generated/launch-flow-truth.md"

TEST_TAG = re.compile(r"(?:Modifier\.)?testTag\(\s*\"([^\"]+)\"\s*\)")
LITERAL = re.compile(r"text\s*=\s*\"([^\"]{2,80})\"")
ERROR = re.compile(r"\"(UI-[A-Z0-9-]+|GPU-[A-Z0-9-]+|MODEL_[A-Z_]+|RUNTIME_[A-Z_]+)\"")
STRING_RES = re.compile(r"<string name=\"([^\"]+)\">([^<]+)</string>")

# Hints are substrings of paths relative to SRC. ModelLibrary must precede
# RuntimeStatus so runtime/modelmanager/*.kt land under ModelLibrary, not runtime/.
LAUNCH_SURFACES = {
    "Onboarding": ["OnboardingScreen", "ui/onboarding"],
    "ChatShell": [
        "ui/ChatApp.kt",
        "ui/ChatScreen.kt",
        "PocketAgentTopBar",
        "MessageBubbleComponents",
        "SessionDrawer",
    ],
    "Composer": ["ChatComposerBar", "ui/ChatScreen.kt"],
    "ModelLibrary": [
        "ModelLibrary",
        "ModelSheet",
        "ModelManagement",
        "ModelProvisioning",
        "ModelOperation",
        "runtime/modelmanager",
    ],
    "Advanced": ["SettingsSheet", "CompletionSettingsSheet", "ui/advanced", "AdvancedSheet"],
    "RuntimeStatus": [
        "ChatStatusHeader",
        "ui/state/ChatUiState.kt",
        "runtime/",
    ],
    "ToolsDialog": ["ToolDialog", "ui/tools", "ToolsDialog"],
    "Diagnostics": ["RuntimeDiagnostics", "ui/diagnostics", "DiagnosticsAction"],
    "VoiceBeta": ["voice/", "ui/voice", "VoiceActivation"],
    "RecoveryBanners": ["UiErrorMapper", "ChatGateState", "ui/recovery", "RuntimeUiState"],
}


def collect_files() -> list[Path]:
    return [p for p in SRC.rglob("*.kt") if p.is_file()]


def by_surface(files: list[Path]) -> dict[str, list[Path]]:
    out: dict[str, list[Path]] = defaultdict(list)
    for f in files:
        rel = f.relative_to(SRC).as_posix()
        for surface, hints in LAUNCH_SURFACES.items():
            if any(h in rel for h in hints):
                out[surface].append(f)
                break
    return out


def matches(files: list[Path], pat: re.Pattern[str]) -> set[str]:
    found: set[str] = set()
    for f in files:
        try:
            text = f.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for m in pat.finditer(text):
            found.add(m.group(1))
    return found


def string_resources() -> dict[str, str]:
    out: dict[str, str] = {}
    for xml in RES.glob("strings*.xml"):
        try:
            raw = xml.read_text(encoding="utf-8")
        except OSError:
            continue
        for m in STRING_RES.finditer(raw):
            out[m.group(1)] = m.group(2)
    return out


def main() -> int:
    files = collect_files()
    surfaced = by_surface(files)
    strings = string_resources()

    lines = [
        "# Launch Flow Truth (Generated From Source)",
        "",
        f"Generated by `tools/qa-agents/code_truth_manifest.py`. Do not edit by hand.",
        "",
        "This file is the **only** authority for selectors, copy, error codes, and",
        "stage transitions used by AI tester sub-agents and Maestro flows. If the",
        "code changes, regenerate this file in the same PR.",
        "",
    ]

    for surface, sfiles in sorted(surfaced.items()):
        lines.append(f"## {surface}")
        lines.append("")
        lines.append(f"Source files ({len(sfiles)}):")
        for f in sfiles:
            lines.append(f"- `{f.relative_to(REPO)}`")
        lines.append("")
        for label, pat in (
            ("testTag", TEST_TAG),
            ("Literal text", LITERAL),
            ("Error codes", ERROR),
        ):
            vals = sorted(matches(sfiles, pat))
            if not vals:
                continue
            lines.append(f"### {label}")
            for v in vals:
                lines.append(f"- `{v}`")
            lines.append("")

    lines.append("## String Resources (launch surfaces)")
    lines.append("")
    for k, v in sorted(strings.items()):
        if any(
            tag in k.lower()
            for tag in (
                "onboard",
                "ready",
                "model",
                "compose",
                "send",
                "retry",
                "advanced",
                "tools",
                "voice",
                "privacy",
                "diagnostic",
                "runtime",
                "gpu",
                "profile",
            )
        ):
            lines.append(f"- `{k}` = \"{v}\"")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
